### ISSUE TITLE
Wrong with client session

### ISSUE THREAD

**Issue by TheSilentDawn** [CaliDog/Axeman#3]
Traceback (most recent call last):
  File "/home/dcs/.local/bin/axeman", line 11, in <module>
    sys.exit(main())
  File "/home/dcs/.local/lib/python3.5/site-packages/axeman/core.py", line 280, in main
    loop.run_until_complete(get_certs_and_print())
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/dcs/.local/lib/python3.5/site-packages/axeman/core.py", line 239, in get_certs_and_print
    with aiohttp.ClientSession(conn_timeout=5) as session:
  File "/home/dcs/.local/lib/python3.5/site-packages/aiohttp/client.py", line 745, in __enter__
    raise TypeError("Use async with instead")
TypeError: Use async with instead
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff03a30fcf8>

**Comment by TheSilentDawn** [comment]
core.py line 239 is wrong
`with aiohttp.ClientSession(conn_timeout=5) as session:`
should be
`async with aiohttp.ClientSession(conn_timeout=5) as session:`

**Comment by ganti** [comment]
this is fixed, close
